export const GET_INVENTORY_WITH_HUB_LOCATIONS = "GET_INVENTORY_WITH_HUB_LOCATIONS";
export const EXPORT_INVENTORY_WITH_HUB_LOCATIONS = "EXPORT_INVENTORY_WITH_HUB_LOCATIONS";
export const CLEAR_INVENTORY_WITH_HUB_LOCATIONS = "CLEAR_INVENTORY_WITH_HUB_LOCATIONS";
export const INVENTORY_WITH_HUB_LOCATIONS_STATISTICS = "INVENTORY_WITH_HUB_LOCATIONS_STATISTICS";
export const VIEW_SKU = "VIEW_SKU";
export const CLEAR_SKU = "CLEAR_SKU";
export const GET_INVENTORY_WITH_HUB_LOCATIONS_IN_ADD_QUANTITY =
  "GET_INVENTORY_WITH_HUB_LOCATIONS_IN_ADD_QUANTITY";
export const CLEAR_GET_INVENTORY_WITH_HUB_LOCATIONS_IN_ADD_QUANTITY =
  "CLEAR_GET_INVENTORY_WITH_HUB_LOCATIONS_IN_ADD_QUANTITY";
export const CLEAR_INVENTORY_WITH_HUB_LOCATIONS_STATISTICS =
  "CLEAR_INVENTORY_WITH_HUB_LOCATIONS_STATISTICS";
