export const GET_CATEGORIES = "GET_CATEGORIES";
export const SYNC_CATEGORIES = "SYNC_CATEGORIES";
export const VIEW_CATEGORY_DETAILS = "VIEW_CATEGORY_DETAILS";
export const GET_CATEGORIES_WITHOUT_TREE = "GET_CATEGORIES_WITHOUT_TREE";
export const CHECK_SYNC_CATEGORY = "CHECK_SYNC_CATEGORY";
