export const GET_ATTRIBUTES = "GET_ATTRIBUTES";
export const SYNC_ATTRIBUTES = "SYNC_ATTRIBUTES";
export const VIEW_ATTRIBUTE = "VIEW_ATTRIBUTE";
export const CLEAR_ATTRIBUTE = "CLEAR_ATTRIBUTE";
export const CHECK_SYNC_ATTRIBUTES = "CHECK_SYNC_ATTRIBUTES";
