import React from "react";
import * as Icon from "react-feather";

const navigationConfig = [
  {
    id: "home",
    title: "Home",
    type: "item",
    icon: <Icon.Home size={20} />,
    navLink: "/",
  },
  {
    id: "users",
    title: "Users",
    type: "item",
    icon: <Icon.Users size={20} />,
    navLink: "/users",
  },
  {
    id: "roles",
    title: "Roles",
    type: "item",
    icon: <Icon.Unlock size={20} />,
    navLink: "/roles",
  },
  {
    id: "appSettings",
    title: "Settings",
    type: "collapse",
    icon: <Icon.Settings size={20} />,
    badge: "primary",
    children: [
      {
        id: "salesChannels",
        title: "Ecommerce",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/settings/ecommerce-channels",
      },
      {
        id: "shippingMethods",
        title: "Shipping",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/settings/shipping-methods",
      },
      {
        id: "editLocale",
        title: "Catalog Lang",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/settings/default-language",
      },
      {
        id: "posIntegrations",
        title: "POS",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/settings/pos",
      },
    ],
  },
  {
    id: "catalog",
    title: "Catalog",
    type: "collapse",
    icon: <Icon.BookOpen size={20} />,
    children: [
      {
        id: "categories",
        title: "Categories",
        type: "item",
        icon: <Icon.Circle size={12} />,
        badge: true,
        navLink: "/catalog/categories",
      },
      {
        id: "attributes",
        title: "Attributes",
        type: "item",
        icon: <Icon.Circle size={12} />,
        badge: true,
        navLink: "/catalog/attributes",
      },
      {
        id: "product",
        title: "Products",
        type: "item",
        icon: <Icon.Circle size={12} />,
        badge: true,
        navLink: "/catalog/products",
      },
    ],
  },
  {
    id: "hubs",
    title: "Hubs",
    type: "item",
    icon: <Icon.Package size={20} />,
    navLink: "/hubs",
  },
  {
    id: "inventory",
    title: "Inventory",
    type: "collapse",

    icon: <Icon.ShoppingBag size={20} />,
    badge: "primary",
    children: [
      {
        id: "totalinventory",
        title: "Total Inventory",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/total-inventory",
      },
      {
        id: "inventory-by-hub",
        title: "Hub Inventory",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/inventory-by-hub",
      },
      {
        id: "locationinventory",
        title: "Location Inventory",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/inventory-by-location",
      },
      {
        id: "moveInventory",
        title: "Moving",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/move-inventory",
      },
      {
        id: "addQuantity",
        title: "Add Quantity",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/add-quantity",
      },
      {
        id: "audit",
        title: "Audit",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/audit",
      },
      {
        id: "productsBuffer",
        title: "Products Buffer",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/products-buffer",
      },
      {
        id: "importing",
        title: "Importing",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/importing",
      },
      {
        id: "soldQuantityLocations",
        title: "Sold Qty Loc",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/sold-quantity-locations",
      },
      {
        id: "refundQuantityLocations",
        title: "Returned Qty Loc",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/inventory/refund-quantity-locations",
      },
    ],
  },
  {
    id: "sales",
    title: "Sales",
    type: "collapse",

    icon: <Icon.Truck size={20} />,
    badge: "primary",
    children: [
      {
        id: "onlineOrders",
        title: "Online Orders",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/sales/online-orders",
      },
      {
        id: "offlineOrders",
        title: "POS Orders",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/sales/offline-orders",
      },
    ],
  },
  {
    id: "fulfillment",
    title: "Fulfillment",
    type: "collapse",
    icon: <Icon.ShoppingCart size={20} />,
    badge: "primary",
    children: [
      {
        id: "cartsList",
        title: "Carts",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/fulfillment/carts",
      },
      {
        id: "dispatchingStations",
        title: "Stations",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/fulfillment/dispatching-list",
      },
    ],
  },
  {
    id: "dispatchingParent",
    title: "Dispatching",
    type: "collapse",
    icon: <Icon.Box size={20} />,
    badge: "primary",
    children: [
      {
        id: "dispatching",
        title: "Dispatch Orders",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/dispatching/dispatch-orders",
      },
      {
        id: "updateShipment",
        title: "Update Shipment",
        type: "item",
        icon: <Icon.Circle size={12} />,
        navLink: "/dispatching/update-shipment",
      },
    ],
  },
];

export default navigationConfig;
