export const CHANGE_MODE = "CHANGE_MODE";
export const COLLAPSE_SIDEBAR = "COLLAPSE_SIDEBAR";
export const CHANGE_NAVBAR_COLOR = "CHANGE_NAVBAR_COLOR";
export const CHANGE_NAVBAR_TYPE = "CHANGE_NAVBAR_TYPE";
export const CHANGE_FOOTER_TYPE = "CHANGE_FOOTER_TYPE";
export const CHANGE_MENU_COLOR = "CHANGE_MENU_COLOR";
export const HIDE_SCROLL_TO_TOP = "HIDE_SCROLL_TO_TOP";
export const CHANGE_DIR = "CHANGE_DIR";
