export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const VIEW_PRODUCT = "VIEW_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const SYNC_PRODUCTS = "SYNC_PRODUCTS";
export const CHECK_SYNC_PRODUCTS = "CHECK_SYNC_PRODUCTS";
export const EXPORT_PRODUCTS = "EXPORT_PRODUCTS";
