export const GET_SOLD_ITEMS="GET_SOLD_ITEMS"
export const DISCARD_SOLD_ITEMS="DISCARD_SOLD_ITEMS" 
export const REMOVE_QUANTITY_TO_INVENTORY="REMOVE_QUANTITY_TO_INVENTORY"
export const CLEAR_SOLD_ITEMS="CLEAR_SOLD_ITEMS"
export const GET_REFUND_ITEMS="GET_REFUND_ITEMS"
export const CLEAR_REFUND_ITEMS="CLEAR_REFUND_ITEMS"
export const  DISCARD_REFUND_ITEMS="DISCARD_REFUND_ITEMS"
export const ADD_QUANTITY_TO_INVENTORY="ADD_QUANTITY_TO_INVENTORY"
export const GET_HUBS="GET_HUBS"
export const CLEAR_HUBS = "CLEAR_HUBS";

