export const GET_DISPATCHING_ORDERS_LIST_STATIONS = "GET_DISPATCHING_ORDERS_LIST_STATIONS";
export const GET_DISPATCHING_FILTER_HUBS = "GET_DISPATCHING_FILTER_HUBS";
export const OCCUPY_STATION = "OCCUPY_STATION";
export const UPDATE_OCCUPATION = "UPDATE_OCCUPATION";
export const CLEAR_DISPATCHING_ORDERS_LIST_STATIONS = "CLEAR_DISPATCHING_ORDERS_LIST_STATIONS";
