export const GET_SETTINGS = "GET_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const SETUP_WIZARD = "SETUP_WIZARD";
export const GET_POS_INTEGRATIONS = "GET_POS_INTEGRATIONS";
export const SHOW_POS_INTEGRATIONS = "SHOW_POS_INTEGRATIONS";
