export const ADD_SERVER_ERROR = "ADD_SERVER_ERROR";
export const REMOVE_SERVER_ERROR = "REMOVE_SERVER_ERROR";
export const CLEAR_SERVER_ERRORS = "CLEAR_SERVER_ERRORS";
export const CHANGE_DOMAIN_CHECKED = "CHANGE_DOMAIN_CHECKED";
export const CHANGE_REMOVE_QUANTITY_ALERT = "CHANGE_REMOVE_QUANTITY_ALERT";
