export const GET_IMPORTING_HUBS = "GET_IMPORTING_HUBS";
export const IMPORT_HUB_LOCATIONS = "IMPORT_HUB_LOCATIONS";
export const SET_LOCATIONS_FILE_SERVER_ERROR = "SET_LOCATIONS_FILE_SERVER_ERROR";
export const SET_BUFFER_FILE_SERVER_ERROR = "SET_BUFFER_FILE_SERVER_ERROR";
export const CLEAR_IMPORTING_BUFFER = "CLEAR_IMPORTING_BUFFER";
export const CLEAR_IMPORTING_LOCATIONS = "CLEAR_IMPORTING_LOCATIONS";
