export const GET_ONLINE_ORDERS = "GET_ONLINE_ORDERS";
export const GET_ONLINE_ORDER_DETAILS = "GET_ONLINE_ORDER_DETAILS";
export const CLEAR_ONLINE_ORDER_DETAILS = "CLEAR_ONLINE_ORDER_DETAILS";
export const GET_SHIPPED_ORDERS = "GET_SHIPPED_ORDERS";
export const GET_UNRESOLVED_ORDERS = "GET_UNRESOLVED_ORDERS";
