export const GET_PRODUCTS_BUFFER_LIST = "GET_PRODUCTS_BUFFER_LIST";
export const CLEAR_PRODUCTS_BUFFER_LIST = "CLEAR_PRODUCTS_BUFFER_LIST";
export const VIEW_SINGLE_PRODUCT_BUFFER = "VIEW_SINGLE_PRODUCT_BUFFER";
export const CLEAR_SINGLE_PRODUCT_BUFFER = "CLEAR_SINGLE_PRODUCT_BUFFER";
